name: Build/release Electron App

on:
  push:
    tags:
      - 'v*.*.*'  # Only run on version tags

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build macOS
        run: npm run electron:build -- --mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-installers
          path: release/*.{dmg,zip}

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Windows build dependencies
        run: |
          npm install --global --production windows-build-tools
          npm install --global node-gyp
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Windows dependencies for canvas
        run: |
          choco install -y python3
          choco install -y gtk-runtime
          choco install -y libjpeg-turbo
          choco install -y giflib
          choco install -y cmake
      - name: Install dependencies
        run: |
          npm ci --platform=win32 --arch=ia32
        env:
          npm_config_arch: ia32
          npm_config_platform: win32
      - name: Build Windows
        run: npm run electron:build -- --win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          npm_config_arch: ia32
          npm_config_platform: win32
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: release/*.{exe,msi}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install system dependencies for canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Install dependencies
        run: npm ci
      - name: Build Linux
        run: npm run electron:build -- --linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-installers
          path: |
            release/*.AppImage
            release/*.{deb,rpm}
