name: Copy Release Assets to Public Repository

# This workflow can be manually triggered to copy release assets from this private repository
# to the public repository for distribution

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag of the release to copy assets from (e.g., v1.0.14)'
        required: true
        default: 'v1.0.14'
      target_release_tag:
        description: 'Tag to use for the release in the public repository (leave empty to use same tag)'
        required: false

jobs:
  copy-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Get release information
        id: get_release
        run: |
          echo "Getting release information for tag: ${{ github.event.inputs.release_tag }}"
          
          # Get all releases and filter by tag (to include draft releases)
          ALL_RELEASES=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases?per_page=100")
          
          # Filter for the specific tag
          RELEASE_INFO=$(echo "$ALL_RELEASES" | jq -r --arg TAG "${{ github.event.inputs.release_tag }}" '.[] | select(.tag_name == $TAG) | .')
          
          # Check if we got valid release info
          if echo "$RELEASE_INFO" | jq -e .id >/dev/null 2>&1; then
            echo "Successfully retrieved release information"
          else
            echo "Error: Failed to retrieve release information for tag ${{ github.event.inputs.release_tag }}"
            echo "Response: $ALL_RELEASES"
            exit 1
          fi
          
          RELEASE_ID=$(echo $RELEASE_INFO | jq -r '.id')
          RELEASE_TAG=$(echo $RELEASE_INFO | jq -r '.tag_name')
          RELEASE_NAME=$(echo $RELEASE_INFO | jq -r '.name')
          RELEASE_BODY=$(echo $RELEASE_INFO | jq -r '.body')
          
          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT
          echo "release_body=$RELEASE_BODY" >> $GITHUB_OUTPUT
          
          echo "Release ID: $RELEASE_ID"
          echo "Release Tag: $RELEASE_TAG"
          echo "Release Name: $RELEASE_NAME"

      - name: Copy assets to public repository
        run: |
          # Get list of assets from source release
          ASSETS_URL="https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release.outputs.release_id }}/assets"
          echo "Fetching assets from: $ASSETS_URL"
          ASSET_LIST=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "$ASSETS_URL")
          
          # Check if we got valid asset list
          if echo "$ASSET_LIST" | jq -e . >/dev/null 2>&1; then
            echo "Successfully retrieved asset list"
          else
            echo "Error: Failed to retrieve asset list"
            echo "Response: $ASSET_LIST"
            exit 1
          fi
          
          # Determine target tag
          if [ -n "${{ github.event.inputs.target_release_tag }}" ] && [ "${{ github.event.inputs.target_release_tag }}" != "" ]; then
            TARGET_TAG="${{ github.event.inputs.target_release_tag }}"
          else
            TARGET_TAG="${{ steps.get_release.outputs.release_tag }}"
          fi
          
          echo "Target tag for public repository: $TARGET_TAG"
          
          # Create release in public repository if it doesn't exist
          PUBLIC_REPO="AkshayAnuOnline/quikballot"
          
          # Check if release already exists
          echo "Checking if release $TARGET_TAG exists in $PUBLIC_REPO"
          RELEASE_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/$PUBLIC_REPO/releases/tags/$TARGET_TAG")
          
          echo "Release exists check returned HTTP status: $RELEASE_EXISTS"
          
          if [ "$RELEASE_EXISTS" = "404" ]; then
            echo "Creating new release $TARGET_TAG in $PUBLIC_REPO"
            # Create new release
            RELEASE_DATA=$(jq -n \
              --arg tag "$TARGET_TAG" \
              --arg name "${{ steps.get_release.outputs.release_name }}" \
              --arg body "${{ steps.get_release.outputs.release_body }}" \
              '{tag_name: $tag, name: $name, body: $body, draft: false, prerelease: false}')
            
            RELEASE_RESPONSE=$(curl -s -X POST \
              -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "$RELEASE_DATA" \
              "https://api.github.com/repos/$PUBLIC_REPO/releases")
            
            # Check if release creation was successful
            if echo "$RELEASE_RESPONSE" | jq -e .id >/dev/null 2>&1; then
              echo "Successfully created release"
            else
              echo "Error: Failed to create release"
              echo "Response: $RELEASE_RESPONSE"
              exit 1
            fi
            
            PUBLIC_RELEASE_ID=$(echo $RELEASE_RESPONSE | jq -r '.id')
            echo "Created release with ID: $PUBLIC_RELEASE_ID"
          else
            echo "Release $TARGET_TAG already exists, getting release ID"
            # Get existing release ID
            PUBLIC_RELEASE_INFO=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
              "https://api.github.com/repos/$PUBLIC_REPO/releases/tags/$TARGET_TAG")
            
            # Check if we got valid release info
            if echo "$PUBLIC_RELEASE_INFO" | jq -e .id >/dev/null 2>&1; then
              echo "Successfully retrieved existing release information"
            else
              echo "Error: Failed to retrieve existing release information"
              echo "Response: $PUBLIC_RELEASE_INFO"
              exit 1
            fi
            
            PUBLIC_RELEASE_ID=$(echo $PUBLIC_RELEASE_INFO | jq -r '.id')
            echo "Existing release ID: $PUBLIC_RELEASE_ID"
          fi
          
          # Copy each asset by downloading first and then uploading
          echo "Copying assets to public repository release $PUBLIC_RELEASE_ID"
          mkdir -p /tmp/assets
          
          echo $ASSET_LIST | jq -c '.[]' | while read asset; do
            ASSET_NAME=$(echo $asset | jq -r '.name')
            ASSET_URL=$(echo $asset | jq -r '.url')
            
            # Skip blockmap and yml files
            if [[ ! "$ASSET_NAME" =~ \.(blockmap|yml)$ ]]; then
              echo "Copying $ASSET_NAME to public repository"
              
              # Download asset to temporary file
              curl -s -L -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                -H "Accept: application/octet-stream" \
                "$ASSET_URL" -o "/tmp/assets/$ASSET_NAME"
              
              # Upload asset to public repository
              curl -s -X POST \
                -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                -H "Content-Type: application/octet-stream" \
                --data-binary @"/tmp/assets/$ASSET_NAME" \
                "https://uploads.github.com/repos/$PUBLIC_REPO/releases/$PUBLIC_RELEASE_ID/assets?name=$ASSET_NAME" > /dev/null
              
              # Clean up temporary file
              rm "/tmp/assets/$ASSET_NAME"
              
              echo "Successfully copied $ASSET_NAME"
            else
              echo "Skipping $ASSET_NAME (blockmap or yml file)"
            fi
          done
          
          # Clean up assets directory
          rm -rf /tmp/assets
          
          echo "Assets copied successfully to public repository release $TARGET_TAG"
