name: Test Token

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test GitHub API access
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}" | \
            jq -r '.name'
      - name: Test Release Creation
        run: |
          RELEASE_DATA=$(jq -n \
            --arg tag "test-token" \
            --arg name "Test Release" \
            '{tag_name: $tag, name: $name, draft: true}')
          
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$RELEASE_DATA" \
            "https://api.github.com/repos/${{ github.repository }}/releases")
          
          echo "$RESPONSE" | jq -r '.id, .tag_name'
          
          # Clean up test release
          RELEASE_ID=$(echo "$RESPONSE" | jq -r '.id')
          if [ "$RELEASE_ID" != "null" ]; then
            curl -s -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"
          fi
